version: '3.7'
services:
  server:
    image: us-central1-docker.pkg.dev/automatic-opus-355008/default/chat-webhook:latest
    ports:
      - 80:3000
    depends_on:
      - databse
      - memory-store
    networks:
      - default-net
  memory-store:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: local_memory_store
    ports:
      - 6379:6379
    networks:
      - default-net
  databse:
    container_name: local_database
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=chat-webhook
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - default-net
networks:
  default-net:
